[2023-08-14 15:04:10,622] {processor.py:153} INFO - Started process (PID=48190) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:04:10,622] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:04:10,623] {logging_mixin.py:115} INFO - [2023-08-14 15:04:10,623] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:04:10,638] {logging_mixin.py:115} INFO - [2023-08-14 15:04:10,637] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:04:10,638] {logging_mixin.py:115} INFO - [2023-08-14 15:04:10,638] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:04:10,638] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:04:10,650] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-08-14 15:08:14,562] {processor.py:153} INFO - Started process (PID=48610) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:08:14,563] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:08:14,564] {logging_mixin.py:115} INFO - [2023-08-14 15:08:14,564] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:08:14,584] {logging_mixin.py:115} INFO - [2023-08-14 15:08:14,583] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:08:14,584] {logging_mixin.py:115} INFO - [2023-08-14 15:08:14,584] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:08:14,584] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:08:14,595] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-08-14 15:08:49,071] {processor.py:153} INFO - Started process (PID=48734) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:08:49,072] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:08:49,073] {logging_mixin.py:115} INFO - [2023-08-14 15:08:49,073] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:08:49,100] {logging_mixin.py:115} INFO - [2023-08-14 15:08:49,099] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:08:49,100] {logging_mixin.py:115} INFO - [2023-08-14 15:08:49,100] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:08:49,100] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:08:49,109] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-08-14 15:09:22,902] {processor.py:153} INFO - Started process (PID=48791) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:09:22,903] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:09:22,904] {logging_mixin.py:115} INFO - [2023-08-14 15:09:22,904] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:09:22,932] {logging_mixin.py:115} INFO - [2023-08-14 15:09:22,931] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:09:22,932] {logging_mixin.py:115} INFO - [2023-08-14 15:09:22,932] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:09:22,933] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:09:22,946] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2023-08-14 15:09:55,626] {processor.py:153} INFO - Started process (PID=48842) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:09:55,627] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:09:55,628] {logging_mixin.py:115} INFO - [2023-08-14 15:09:55,628] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:09:55,642] {logging_mixin.py:115} INFO - [2023-08-14 15:09:55,641] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:09:55,642] {logging_mixin.py:115} INFO - [2023-08-14 15:09:55,642] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:09:55,642] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:09:55,652] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-08-14 15:10:28,839] {processor.py:153} INFO - Started process (PID=48901) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:10:28,840] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:10:28,840] {logging_mixin.py:115} INFO - [2023-08-14 15:10:28,840] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:10:28,854] {logging_mixin.py:115} INFO - [2023-08-14 15:10:28,854] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:10:28,854] {logging_mixin.py:115} INFO - [2023-08-14 15:10:28,854] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:10:28,855] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:10:28,867] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-08-14 15:11:04,054] {processor.py:153} INFO - Started process (PID=48950) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:11:04,056] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:11:04,057] {logging_mixin.py:115} INFO - [2023-08-14 15:11:04,057] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:11:04,081] {logging_mixin.py:115} INFO - [2023-08-14 15:11:04,080] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:11:04,081] {logging_mixin.py:115} INFO - [2023-08-14 15:11:04,081] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:11:04,081] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:11:04,093] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-08-14 15:11:38,139] {processor.py:153} INFO - Started process (PID=49000) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:11:38,140] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:11:38,141] {logging_mixin.py:115} INFO - [2023-08-14 15:11:38,141] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:11:38,169] {logging_mixin.py:115} INFO - [2023-08-14 15:11:38,168] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:11:38,170] {logging_mixin.py:115} INFO - [2023-08-14 15:11:38,169] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:11:38,170] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:11:38,193] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2023-08-14 15:12:10,253] {processor.py:153} INFO - Started process (PID=49044) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:12:10,255] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:12:10,256] {logging_mixin.py:115} INFO - [2023-08-14 15:12:10,256] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:12:10,279] {logging_mixin.py:115} INFO - [2023-08-14 15:12:10,279] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:12:10,279] {logging_mixin.py:115} INFO - [2023-08-14 15:12:10,279] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:12:10,279] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:12:10,291] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-08-14 15:12:43,411] {processor.py:153} INFO - Started process (PID=49096) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:12:43,412] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:12:43,412] {logging_mixin.py:115} INFO - [2023-08-14 15:12:43,412] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:12:43,442] {logging_mixin.py:115} INFO - [2023-08-14 15:12:43,441] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:12:43,442] {logging_mixin.py:115} INFO - [2023-08-14 15:12:43,442] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:12:43,442] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:12:43,451] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-08-14 15:13:18,296] {processor.py:153} INFO - Started process (PID=49144) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:13:18,296] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:13:18,297] {logging_mixin.py:115} INFO - [2023-08-14 15:13:18,297] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:13:18,312] {logging_mixin.py:115} INFO - [2023-08-14 15:13:18,312] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:13:18,312] {logging_mixin.py:115} INFO - [2023-08-14 15:13:18,312] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:13:18,312] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:13:18,324] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-08-14 15:13:53,925] {processor.py:153} INFO - Started process (PID=49197) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:13:53,926] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:13:53,926] {logging_mixin.py:115} INFO - [2023-08-14 15:13:53,926] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:13:53,945] {logging_mixin.py:115} INFO - [2023-08-14 15:13:53,944] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:13:53,945] {logging_mixin.py:115} INFO - [2023-08-14 15:13:53,945] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:13:53,945] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:13:53,961] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-08-14 15:14:28,331] {processor.py:153} INFO - Started process (PID=49246) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:14:28,332] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:14:28,333] {logging_mixin.py:115} INFO - [2023-08-14 15:14:28,333] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:14:28,351] {logging_mixin.py:115} INFO - [2023-08-14 15:14:28,351] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:14:28,351] {logging_mixin.py:115} INFO - [2023-08-14 15:14:28,351] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:14:28,352] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:14:28,363] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-08-14 15:15:01,131] {processor.py:153} INFO - Started process (PID=49299) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:15:01,132] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:15:01,133] {logging_mixin.py:115} INFO - [2023-08-14 15:15:01,132] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:15:01,166] {logging_mixin.py:115} INFO - [2023-08-14 15:15:01,165] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:15:01,166] {logging_mixin.py:115} INFO - [2023-08-14 15:15:01,166] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:15:01,166] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:15:01,182] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2023-08-14 15:15:33,674] {processor.py:153} INFO - Started process (PID=49347) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:15:33,676] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:15:33,677] {logging_mixin.py:115} INFO - [2023-08-14 15:15:33,677] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:15:33,702] {logging_mixin.py:115} INFO - [2023-08-14 15:15:33,701] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:15:33,702] {logging_mixin.py:115} INFO - [2023-08-14 15:15:33,702] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:15:33,702] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:15:33,716] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-08-14 15:16:06,843] {processor.py:153} INFO - Started process (PID=49398) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:16:06,844] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:16:06,845] {logging_mixin.py:115} INFO - [2023-08-14 15:16:06,845] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:16:06,860] {logging_mixin.py:115} INFO - [2023-08-14 15:16:06,859] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:16:06,860] {logging_mixin.py:115} INFO - [2023-08-14 15:16:06,860] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:16:06,860] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:16:06,869] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-08-14 15:16:39,446] {processor.py:153} INFO - Started process (PID=49443) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:16:39,446] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:16:39,447] {logging_mixin.py:115} INFO - [2023-08-14 15:16:39,447] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:16:39,460] {logging_mixin.py:115} INFO - [2023-08-14 15:16:39,460] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:16:39,461] {logging_mixin.py:115} INFO - [2023-08-14 15:16:39,461] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:16:39,461] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:16:39,472] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-08-14 15:17:12,829] {processor.py:153} INFO - Started process (PID=49494) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:17:12,830] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:17:12,831] {logging_mixin.py:115} INFO - [2023-08-14 15:17:12,831] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:17:12,865] {logging_mixin.py:115} INFO - [2023-08-14 15:17:12,864] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:17:12,865] {logging_mixin.py:115} INFO - [2023-08-14 15:17:12,865] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:17:12,866] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:17:12,885] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2023-08-14 15:17:47,636] {processor.py:153} INFO - Started process (PID=49542) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:17:47,637] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:17:47,637] {logging_mixin.py:115} INFO - [2023-08-14 15:17:47,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:17:47,653] {logging_mixin.py:115} INFO - [2023-08-14 15:17:47,653] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:17:47,654] {logging_mixin.py:115} INFO - [2023-08-14 15:17:47,654] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:17:47,654] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:17:47,664] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-08-14 15:18:19,809] {processor.py:153} INFO - Started process (PID=49591) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:18:19,811] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:18:19,811] {logging_mixin.py:115} INFO - [2023-08-14 15:18:19,811] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:18:19,824] {logging_mixin.py:115} INFO - [2023-08-14 15:18:19,823] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:18:19,824] {logging_mixin.py:115} INFO - [2023-08-14 15:18:19,824] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:18:19,824] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:18:19,836] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-08-14 15:18:54,687] {processor.py:153} INFO - Started process (PID=49642) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:18:54,687] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:18:54,688] {logging_mixin.py:115} INFO - [2023-08-14 15:18:54,688] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:18:54,702] {logging_mixin.py:115} INFO - [2023-08-14 15:18:54,702] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:18:54,702] {logging_mixin.py:115} INFO - [2023-08-14 15:18:54,702] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:18:54,702] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:18:54,713] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-08-14 15:19:28,858] {processor.py:153} INFO - Started process (PID=49688) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:19:28,859] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:19:28,859] {logging_mixin.py:115} INFO - [2023-08-14 15:19:28,859] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:19:28,881] {logging_mixin.py:115} INFO - [2023-08-14 15:19:28,881] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:19:28,881] {logging_mixin.py:115} INFO - [2023-08-14 15:19:28,881] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:19:28,882] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:19:28,892] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-08-14 15:20:02,659] {processor.py:153} INFO - Started process (PID=49740) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:20:02,660] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:20:02,660] {logging_mixin.py:115} INFO - [2023-08-14 15:20:02,660] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:20:02,679] {logging_mixin.py:115} INFO - [2023-08-14 15:20:02,679] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:20:02,679] {logging_mixin.py:115} INFO - [2023-08-14 15:20:02,679] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:20:02,680] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:20:02,690] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-08-14 15:20:33,485] {processor.py:153} INFO - Started process (PID=49789) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:20:33,485] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:20:33,486] {logging_mixin.py:115} INFO - [2023-08-14 15:20:33,486] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:20:33,507] {logging_mixin.py:115} INFO - [2023-08-14 15:20:33,506] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:20:33,507] {logging_mixin.py:115} INFO - [2023-08-14 15:20:33,507] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:20:33,507] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:20:33,527] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-08-14 15:21:07,426] {processor.py:153} INFO - Started process (PID=49839) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:21:07,428] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:21:07,428] {logging_mixin.py:115} INFO - [2023-08-14 15:21:07,428] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:21:07,454] {logging_mixin.py:115} INFO - [2023-08-14 15:21:07,454] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:21:07,454] {logging_mixin.py:115} INFO - [2023-08-14 15:21:07,454] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:21:07,455] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:21:07,465] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-08-14 15:21:43,535] {processor.py:153} INFO - Started process (PID=49891) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:21:43,537] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:21:43,538] {logging_mixin.py:115} INFO - [2023-08-14 15:21:43,538] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:21:43,568] {logging_mixin.py:115} INFO - [2023-08-14 15:21:43,567] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:21:43,569] {logging_mixin.py:115} INFO - [2023-08-14 15:21:43,568] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:21:43,569] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:21:43,590] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-08-14 15:22:19,197] {processor.py:153} INFO - Started process (PID=49947) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:22:19,197] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:22:19,198] {logging_mixin.py:115} INFO - [2023-08-14 15:22:19,198] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:22:19,212] {logging_mixin.py:115} INFO - [2023-08-14 15:22:19,212] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:22:19,213] {logging_mixin.py:115} INFO - [2023-08-14 15:22:19,212] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:22:19,213] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:22:19,223] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-08-14 15:22:53,004] {processor.py:153} INFO - Started process (PID=49997) to work on /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:22:53,005] {processor.py:641} INFO - Processing file /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-14 15:22:53,005] {logging_mixin.py:115} INFO - [2023-08-14 15:22:53,005] {dagbag.py:507} INFO - Filling up the DagBag from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:22:53,027] {logging_mixin.py:115} INFO - [2023-08-14 15:22:53,026] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-14 15:22:53,027] {logging_mixin.py:115} INFO - [2023-08-14 15:22:53,027] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-14 15:22:53,027] {processor.py:653} WARNING - No viable dags retrieved from /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-14 15:22:53,047] {processor.py:161} INFO - Processing /home/salerno/Documents/airflow_test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
